"""
Sentiment Analysis App
----------------------
A Streamlit interface for a TF-IDF + Logistic Regression sentiment
classification model.

Run locally with:
    streamlit run app.py
"""

import pickle
from pathlib import Path

import streamlit as st

# --------------------------------------------------------------------------
# Page configuration
# --------------------------------------------------------------------------
st.set_page_config(
    page_title="Sentiment Analyzer",
    page_icon="💬",
    layout="centered",
    initial_sidebar_state="expanded",
)

MODEL_PATH = Path(__file__).parent / "model.pkl"
VECTORIZER_PATH = Path(__file__).parent / "vectorizer.pkl"


# --------------------------------------------------------------------------
# Cached resource loading
# --------------------------------------------------------------------------
@st.cache_resource(show_spinner="Loading model...")
def load_artifacts():
    """Load the trained model and vectorizer once, then cache them."""
    with open(MODEL_PATH, "rb") as f:
        model = pickle.load(f)
    with open(VECTORIZER_PATH, "rb") as f:
        vectorizer = pickle.load(f)
    return model, vectorizer


def predict_sentiment(text: str, model, vectorizer):
    """Vectorize input text and return the predicted label + probabilities."""
    features = vectorizer.transform([text])
    prediction = model.predict(features)[0]

    probabilities = None
    if hasattr(model, "predict_proba"):
        proba = model.predict_proba(features)[0]
        probabilities = dict(zip(model.classes_, proba))

    return prediction, probabilities


# --------------------------------------------------------------------------
# Sidebar
# --------------------------------------------------------------------------
with st.sidebar:
    st.title("💬 Sentiment Analyzer")
    st.markdown(
        """
        This app uses a **TF-IDF Vectorizer** combined with a
        **Logistic Regression** classifier to predict whether a
        piece of text expresses **positive** or **negative** sentiment.

        **How to use:**
        1. Enter or paste text in the box.
        2. Click **Analyze Sentiment**.
        3. View the predicted label and confidence score.
        """
    )
    st.divider()
    st.caption("Built with Streamlit · scikit-learn")


# --------------------------------------------------------------------------
# Main content
# --------------------------------------------------------------------------
st.title("Sentiment Analysis")
st.markdown("Enter some text below to analyze its sentiment.")

# Load model artifacts (cached — only runs once per session)
try:
    model, vectorizer = load_artifacts()
except FileNotFoundError:
    st.error(
        "Model files not found. Please make sure `model.pkl` and "
        "`vectorizer.pkl` are in the same directory as `app.py`."
    )
    st.stop()

# Text input
user_input = st.text_area(
    "Your text",
    height=150,
    placeholder="Type or paste text here (e.g. a product review, tweet, or comment)...",
    label_visibility="collapsed",
)

col1, col2 = st.columns([1, 1])
with col1:
    analyze_clicked = st.button("Analyze Sentiment", type="primary", use_container_width=True)
with col2:
    clear_clicked = st.button("Clear", use_container_width=True)

if clear_clicked:
    st.rerun()

# --------------------------------------------------------------------------
# Prediction and results
# --------------------------------------------------------------------------
if analyze_clicked:
    if not user_input.strip():
        st.warning("Please enter some text before analyzing.")
    else:
        with st.spinner("Analyzing..."):
            prediction, probabilities = predict_sentiment(user_input, model, vectorizer)

        st.divider()
        st.subheader("Result")

        # Display predicted label as a styled badge
        if str(prediction).lower() == "positive":
            st.success(f"**Predicted Sentiment: Positive** 😊")
        elif str(prediction).lower() == "negative":
            st.error(f"**Predicted Sentiment: Negative** 😞")
        else:
            st.info(f"**Predicted Sentiment: {prediction}**")

        # Display confidence scores if available
        if probabilities:
            st.markdown("#### Confidence Scores")
            for label, prob in sorted(probabilities.items(), key=lambda x: -x[1]):
                st.write(f"{label.capitalize()}")
                st.progress(float(prob), text=f"{prob:.1%}")

st.divider()
st.caption(
    "Note: Predictions are generated by a machine learning model and may "
    "not always be accurate. Use results as guidance, not ground truth."
)
